# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST /hello HTTP/1.1
Host: 3000-hebertcisco-deploypytho-jd9aomhlkk8.ws-us89.gitpod.io
Content-Type: application/json
Content-Length: 28

{
    "message": "Fulano!"
}